environment:
  GITHUB_API_URL: https://api.github.com
  SECRETS_NAME: <AWS_SECRETS_MANAGER_SECRET_NAME>
  REGION: <AWS_REGION_NAME>

region: <AWS_REGION_NAME>

account_id: <AWS_ACCOUNT_ID>

vpc:
  securityGroupIds:
    - sg-<security_group_id>
  subnetIds:
    - subnet-<subnet_id>
    - subnet-<subnet_id>

resourcePolicy:
  - Effect: Allow
    Principal: "*"
    Action: execute-api:Invoke
    Resource:
      - execute-api:/*/*
    Condition:
      IpAddress:
        aws:SourceIp:
            - "" # some IP